version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
